# SPDX-License-Identifier: Apache-2.0

manifest:
  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      revision: v3.7.0
      path: zephyr
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
        path-prefix: zephyr_os   # applied to zephyr + all imported modules → zephyr_os/

  self:
    west-commands: scripts/west-commands.yml
