CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y

CONFIG_PWM=y
CONFIG_PWM_SERVO=y

#CONFIG_RC=y
#CONFIG_RC_SBUS=y
CONFIG_INPUT=y
CONFIG_INPUT_SBUS_RECEIVER=y
# CONFIG_INPUT_MODE_SYNCHRONOUS ??

CONFIG_ADC=y

CONFIG_SENSOR=y
CONFIG_QDEC_STM32=y
CONFIG_STM32_TEMP=y

CONFIG_MOTOR=y
CONFIG_MOTOR_HBRIDGE=y

CONFIG_SHELL=y
#CONFIG_SHELL_GETOPT=y
CONFIG_PWM_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_SENSOR_SHELL=y
CONFIG_ADC_SHELL=y

CONFIG_THREAD_ANALYZER=y
#CONFIG_THREAD_ANALYZER_USE_PRINTK=y
#CONFIG_THREAD_ANALYZER_AUTO=y
#CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5

CONFIG_LOG=y
CONFIG_MOTOR_LOG_LEVEL_DBG=y

#CONFIG_NEWLIB_LIBC=y
#CONFIG_PICOLIBC=n
CONFIG_CBPRINTF_FP_SUPPORT=y
